function sr = resetparam_4Pi_fit(offsetfile,Fm,bxsz,trans)
coeff = permute(Fm.coeff,[6,5,4,3,2,1]);
Tm = double(cat(3,eye(3,3),permute(Fm.T,[3,2,1])));
pz = Fm.pixelsize_z*1e3;
pxsz = Fm.pixelsize_x*1e3;
zT = Fm.zT;
ccz = size(coeff,3)/2;
sr.Gainpath = offsetfile;
sr.Peakthresh = 6;
sr.LocTransform = Tm;
sr.Boxsize = bxsz;
sr.Quadshift = trans;
sr.Gain = 2.27;
sr.Phi0 = [0 ,0, 0, 0];
sr.Dz = [0,0,0,0];
sr.Dphi = [0,0,0,0];
sr.BGoffset = 0;
sr.InitPhase = [0,1].*pi;
sr.Initz = [-1,1]*150/pz+ccz;
sr.Initx = [];
sr.Zcenter = ccz;
sr.IABall = coeff;
sr.Pixelsize = pxsz;%nm
pt = zT/2/pi*pz;
sr.Pixelsizez = pz; % nm
sr.Pixelsizeang = pt;% radian to nm
sr.Periodz = zT*pz; % nm
sr.updateTflag = 0;
