function sr = resetparam_4Pi_fit(offsetfile,calfile,bxsz,trans)
val=loadh5(calfile);
params = jsondecode(h5readatt(calfile,'/','params'));
%     fitpar.splinefit{1}.dz=params.pixelsize_z*1000;
%     fitpar.splinefit{1}.coeff=squeeze(permute(val.locres.coeff,[6,5,4,3,2,1]));
%     fitpar.splinefit{1}.z0=ceil(size(val.locres.coeff,3)/2);
% fitpar.dz=params.pixelsize_z*1000;
% fitpar.z0=fitpar.splinefit{1}.z0;
% fitpar.mode='cspline';


coeff = squeeze(permute(val.locres.coeff,[6,5,4,3,2,1]));
Tm = double(cat(3,eye(3,3),permute(val.res.T,[3,2,1])));
pz = params.pixelsize_z*1000;
pxsz = params.pixelsize_x*1e3;
zT = params.modulation_period;
ccz = size(coeff,3)/2;
sr.Gainpath = offsetfile;
sr.Peakthresh = 6;
sr.LocTransform = Tm;
sr.Boxsize = bxsz;
sr.Quadshift = trans;
sr.Gain = 2.27;
sr.Phi0 = [0 ,0, 0, 0];
sr.Dz = [0,0,0,0];
sr.Dphi = [0,0,0,0];
sr.BGoffset = 0;
sr.InitPhase = [0,1/3,2/3].*pi;
sr.Initz = [0]*150/pz+ccz;
sr.Initx = [];
sr.Zcenter = ccz;
sr.IABall = coeff;
sr.Pixelsize = pxsz;%nm
pt = zT/2/pi*pz;
sr.Pixelsizez = pz; % nm
sr.Pixelsizeang = pt;% radian to nm
sr.Periodz = zT*pz; % nm
sr.zT=zT;
sr.updateTflag = 0;
