global se
ac=0*se.sites(1).evaluation.NPCgeomtryQuantify.ac;
z=se.sites(2).evaluation.NPCgeomtryQuantify.z;
d=se.sites(1).evaluation.NPCgeomtryQuantify.Gaussfit.d;
zposall=-300:10:300;
zposall=0;
for j=1:length(zposall)
    zpos=zposall(j);
dzpos=50;
count=0;
for k=1:length(se.sites)
    
    if (se.sites(k).pos(3))<zpos+dzpos && (se.sites(k).pos(3))>zpos-dzpos
    ac=ac+se.sites(k).evaluation.NPCgeomtryQuantify.ac;
    
    count=count+1;
    d(count)=abs(se.sites(k).evaluation.NPCgeomtryQuantify.Gaussfit.d);
    end
end
ac=ac/count;
% figure(88);
l=ceil(length(ac)/2);
zh=z(end-l+2:end);
ach=ac(2:l);
% hold off
% plot(zh,(ach)/max(abs(ach)));
% hold on
% dach=diff(ach);
% ddach=diff(dach);
% dz=z(2)-z(1);
% plot(zh(1:end-1)+dz/2,(dach)/max(abs(dach)));
% plot(zh(1:end-2)+dz,(ddach)/max(abs(ddach)));
% ac=getFieldAsVector(se.sites,{'evaluation','NPCgeomtryQuantify','ac'})
[fitresult, gof] = createFit(zh, ach);
title(fitresult.b2)
posm(j)=fitresult.b2;

end
figure(89)
hist(d,0:5:200)
title([median(d),mean(d)])
figure(88)
plot(zposall,posm)

function [fitresult, gof] = createFit(zh, ach)
%CREATEFIT(ZH,ACH)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : zh
%      Y Output: ach
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 14-Dec-2016 10:27:03


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( zh, ach );

% Set up fittype and options.
ft = fittype( 'gauss3' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 0 -Inf 10 0 -Inf 0 1e5];
opts.StartPoint = [max(ach)/2 50 25. max(ach)/2 100 28. 0 0 1e5];
opts.Upper = [Inf 0 Inf Inf Inf Inf Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure(99);
h = plot( fitresult, xData, yData );
legend( h, 'ach vs. zh', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel zh
ylabel ach
grid on
end
